/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Api
 * CineBodha API specification
 * OpenAPI spec version: 0.1.0
 */
export interface HealthStatus {
  status: string;
}

export interface Video {
  id: number;
  title: string;
  titleTelugu: string;
  category: string;
  duration: string;
  views: string;
  thumbnail: string;
  youtubeUrl: string;
  publishedAt: string;
}

export interface Topic {
  id: number;
  name: string;
  nameTelugu: string;
  description: string;
  icon: string;
  image: string;
  tag: string;
}

export interface ChannelStats {
  subscribers: string;
  videos: string;
  views: string;
  years: string;
}
